services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: repsy_db
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: ates
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - repsy-net

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - repsy-net

  repsy:
    image: repsy:latest
    container_name: repsy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repsy_db
      SPRING_DATASOURCE_USERNAME: furkan
      SPRING_DATASOURCE_PASSWORD: ates
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      STORAGE_STRATEGY: object-storage
    volumes:
      - ./repsy_storage:/storage/repsy_storage
    networks:
      - repsy-net
    depends_on:
      - postgres
      - minio

networks:
  repsy-net:

volumes:
  postgres-data:
  minio-data:
